# Generated by Django 3.2.9 on 2021-12-01 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_advertisement'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='view_num',
            field=models.IntegerField(default=0),
        ),
    ]
